# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: "mysql:5.7"
    ports:
      - '3310:3306'
    environment:
       - MYSQL_USER=user
       - MYSQL_PASSWORD=1234
       - MYSQL_DATABASE=silly
       - MYSQL_ROOT_PASSWORD=1234